version: '2'
services:
    warehouse-postgresql:
        container_name: warehouse-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/warehouse/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=warehouse
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
